volumes:
    localstack-data:
        name: localstack-data

services:
    localstack:
        container_name: localstack
        image: localstack/localstack:2.2
        ports:
            - '4566:4566'
        environment:
            DEBUG: 1
            PERSISTENCE: 1
        volumes:
            - type: volume
              source: localstack-data
              target: /var/lib/localstack
            - type: bind
              source: /var/run/docker.sock
              target: /var/run/docker.sock
